### ISSUE TITLE
XKB layout undetected when installed, works fine only via run-session.sh

### ISSUE THREAD

**Issue by disk0x** [39aldo39/klfc#12]
I have a keyboard layout which when compiled into XKB and installed via install-system.sh goes undetected and is not usable (files are copied in /usr/share/X11/xkb/ correctly by the script, and Xorg is restarted just in case).
The same layout works fine via run-session.sh. Other keyboard layouts created with klfc also work fine even when installed. 

I suspected the use of modifying characters to be the problem, but even when they are removed, the exact same problem persists.  The json description looks fine to me, and the generated symbols file as well. So I don't know why this doesn't work. Is there something that breaks klfc in the layout description?

klfc versions tried: 1.5.1, 1.5.0, 1.4.4
OS: Fedora 27, Fedora 26

* * * 

EDIT: The non-released change in commit 67198cf appears to fix my problem.

**Comment by 39aldo39** [comment]
As you noted, the latest commit fixed the issue. I have published a new release (v1.5.2) for it.
