### ISSUE TITLE
Variants and Mods not showing

### ISSUE THREAD

**Issue by nstetter** [39aldo39/klfc#19]
Hi,

I hope this isn't a stupid question, but I can't grasp how to use modifiers and variants.

For testing I tried to get a Colemak layout with the DH-mod variant and a wide mod by running:

    $klfc colemak.json mods.json --xkb xkb-out

and then installing via the provided `install-system.sh` script.

But when selecting Colemak layout in my GUI layout options (KDE Plasma 5.12) it doesn't show variants:

![keyboard](https://user-images.githubusercontent.com/21746115/51554606-f0b65980-1e75-11e9-9421-103bc5d52fc6.png)

Same result in the command line:

    $localectl list-x11-keymap-variants | grep colemak
    $colemak

What am I doing wrong here?

**Comment by 39aldo39** [comment]
You are right, mods and variants are currently not shown in the UI with `install-sytem.sh`. I think I started working on it, but didn't finish it.

As a workaround, you can use either the `run-session.sh` script as
`./run-session.sh -m Wide -v mod-dh`
or, after installing,
`setxkbmap -layout colemak -keycodes "colemak(Wide)" -variant mod-dh`

**Comment by nstetter** [comment]
Thanks for the explanation.

Is it possible to combine mods? Like using 'Wide' and 'Angle' together? Or would I have to create a separate mod 'Wide Angle'?

Also are you planning on finishing the feature for showing mods and variants un the UI? Would be very much appreciated.

**Comment by nstetter** [comment]
Also I don't really understand what distinguishes mods and variants. In which order are they applied, if I use a variant and a mod?

**Comment by 39aldo39** [comment]
> Is it possible to combine mods? Like using 'Wide' and 'Angle' together? Or would I have to create a separate mod 'Wide Angle'?

Yes, you can! You can use the option `--combine-mods`. If you use the option without an output, it will add `WideAngle` to the list of mods. This also allows you to modify it (maybe not needed).

> Also are you planning on finishing the feature for showing mods and variants un the UI? Would be very much appreciated.

I am, but somewhere in the coming few weeks.

> Also I don't really understand what distinguishes mods and variants. In which order are they applied, if I use a variant and a mod?

Mods and variants are slightly different. Mods will rearrange all keys. This means they are the same for all layouts, and apply to all layers. Variants just add some extra key definitions. This is mostly relevant for the extend layer. If you apply the mod Wide, you want it to apply to the extend layer as well. However, with the variant mod-dh, you don't want that.

They are also implemented differently. For example, mods are applied in games, but variants aren't (if the game implements it correctly).

**Comment by DreymaR** [comment]
With the dh mod I recommend moving the Extend Ctrl+V key to V, so I use a special CurlAngle variant. It's a bit messy but I think it's needed.

**Comment by 39aldo39** [comment]
I have improved the installation scripts in v1.5.4. The mods and variants will now be visible. The mod can be selected from the "Hardware" tab.

**Comment by nstetter** [comment]
Thank you very much for your time and effort
