### ISSUE TITLE
parse from xkb fails

### ISSUE THREAD

**Issue by kjagodka** [39aldo39/klfc#20]
Parsing xkb in builds 1.4.3 and newer fails.
`$ ./klfc --from-xkb "/usr/share/X11/xkb/symbols/us(basic)" --pkl PKL`
`klfc: parse fail in /usr/share/X11/xkb/symbols/us:2:21:`
`unexpected '{'`
`expecting '"'`
Same command works just fine in builds 1.4.2 and older.

**Comment by 39aldo39** [comment]
Thanks for the report. Knowing that the bug happens between 1.4.2 and 1.4.3 really helped. (The problem happened in 3da71c3.) It is fixed now.

**Comment by ThorErikEsi** [comment]
Exact same behaviour happens in 1.5.3
