### ISSUE TITLE
parse from xkb fails

### ISSUE THREAD

**Issue by ldevillez** [39aldo39/klfc#21]
```
> klfc --from-xkb "fr(bepo)" --json test
klfc: parse fail in ./fr:2:21:
unexpected '{'
expecting '"'
```

hello, i've got an error when i try to convert my layout (bepo) to a json (i've got this error with the version 1.5.3 and 1.5.4). I've seen that this error was resolve with 3da71c3

Thanks in advance

**Comment by 39aldo39** [comment]
Thanks for the notice! I have now published a new version.
