### ISSUE TITLE
Cancle latch status for modifier keys?

### ISSUE THREAD

**Issue by AmaiKinono** [39aldo39/klfc#23]
I am using `latch:` options for all my modifier keys. Sometimes I hit a modifier key by accident and want to cancel it. Is there anyway to do it in klfc? or it's not supported by xkb?

Thanks!

**Comment by DreymaR** [comment]
Does the Escape key help?

**Comment by AmaiKinono** [comment]
No, it works like `modifier key + Esc`.

**Comment by 39aldo39** [comment]
Unfortunately I can currently not test it on Linux, but I have two suggestions:
- It should work like sticky keys (but just on single keys). According to [this question](https://superuser.com/questions/693875/sticky-keys-how-do-you-cancel-a-modifier-key) it may be possible to cancel it by pressing the key *twice*.
- If that doesn't work, you can also try mapping an unused key to `""`. If you then press that key, it should register as `modifier + VoidSymbol` which shouldn't do anything.

**Comment by AmaiKinono** [comment]
Thanks for your help! Pressing twice doesn't cancel it (would be wonderful if it does). I also tried mapping Ctrl + Ctrl to `" "` (using layer), that doesn't help either. Mapping an unused key to `" "` seems a good idea, I will do that.

**Comment by AmaiKinono** [comment]
> try mapping an unused key to `""`.

Yes, I can confirm this works. Feel free to close this issue, or leave it for further test/discussion.
