### ISSUE TITLE
Bind a key to lock a modifier

### ISSUE THREAD

**Issue by noctuid** [39aldo39/klfc#3]
XKB supports locking modifiers with `LockMods`. It would be nice if there was a way to bind a key to toggle arbitrary modifiers (besides capslock/numlock) using this.

**Comment by 39aldo39** [comment]
I have added support for locking arbitrary modifiers. To lock a modifier, use 'lock:modifier'.

**Comment by noctuid** [comment]
Thank you. It's nice to have `latch:`available as well.
