### ISSUE TITLE
Space as modifier key without losing space functionality

### ISSUE THREAD

**Issue by Pomegranate123** [39aldo39/klfc#30]
I'm trying to make a layout where if you hold space, it activates the Extend layer, but if you tap space it'll just put a space. Is this possible with KLFC? I'm trying to export it as an xkb file when it's done, if that helps. Maybe I could manually edit something in the xkb files to add the functionality if it isn't supported by KLFC?

**Comment by 39aldo39** [comment]
Unfortunately, this feature is not possible in XKB. You have to use an external program or program the keyboard directly if you really want it.

**Comment by wismill** [comment]
You may be interested in [Kmonad](https://github.com/david-janssen/kmonad)
