### ISSUE TITLE
[Enhancement] Uninstall script 

### ISSUE THREAD

**Issue by disk0x** [39aldo39/klfc#9]
First of all, amazing piece of software, thanks for developing this. I'm using it to help a highly endangered regional language. 

I have an enhancement suggestion, an uninstall script for generated (xkb) layouts would be a good addition. Most of the files the install scripts are easy to remove manually, except the base.xml and evdev.xml in-situ modifications. 

I suppose similar scripts would also be beneficial for the other keyboard layout formats this software generates.

**Comment by 39aldo39** [comment]
Thanks for the suggestion. I have added uninstall scripts for XKB, among other improvements.
